### ISSUE TITLE
Notes from meeting on 2018-07-05

### ISSUE THREAD

**Issue by coderberry** [sustainers/events#8] opened 2018-07-05 15:31 UTC
### Attendees:

* Gunnar
* Justin
* Pia
* Eric

### General discussion points:

We want to let companies know that no more than 2 attendees per company. Every person is responsible to buy their own ticket.

There is an urgency behind getting the rebranding of the website and communications completed.

SustainOSS.org should contain report, pictures, and this years event sub-domain. It’s great for people to see the history and read report. We could use subdomains (SF2017, UK 2018, etc) or a path (/2018/london). Copyright for main org could be used from collective (as base holder) and we can return to it once we have a better narrative.

### Action items:

* [x] @jdorfman - Send Eli what we have along with goals for sustain
* [ ] @piamancini - Reach out to Cat and Josh to make sure it’s OK on their end (I'm unsure what this means)
* [ ] (team) - Begin deciding who to invite for the travel applications
    - Reach out to communities and projects that are most depended on. Tell them "We have a travel fund. Please apply"
* [ ] @piamancini - Make a big spreadsheet of candidates over the next week so we can go through and pick 30-40 (?) of initial outreach and ask them “Who do you think should be there to make it more diverse?”
* [x] @piamancini - Pick 10 people from list from last year and add to that with possibles and invite them to comment on values, and ask who to invite
* [ ] @jdorfman - Add column for each person in spreadsheet (copied) for voting

**Comment by jdorfman** [comment] 2018-07-09 17:23
> Add column for each person in spreadsheet (copied) for voting

@coderberry what is the column name?

**Comment by piamancini** [comment] 2018-07-11 08:52
@jdorfman can you share a duplicate of the attendee list so we can make make an initial outreach for diversity? 
thanks!

**Comment by jdorfman** [comment] 2018-07-11 16:34
@piamancini you're in =)

**Closed as completed** 2018-10-25 23:44 UTC
